env:
  image_name: public/patroni-exporter

name: Push to Registry

on:
  push:
    branches:
      - 'master'
      - 'dev'
    tags:
      - '*'

jobs:
  docker:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    name: Push Docker Image
    runs-on: ubuntu-18.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Login to Harbor
        run: docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin <<< "$DOCKER_PASSWORD"

      - name: Build
        run: docker build -t ${DOCKER_REGISTRY}/${image_name}:${GITHUB_SHA::8} .

      - name: Tag (dev)
        if: github.ref == 'refs/heads/dev'
        run: docker tag ${DOCKER_REGISTRY}/${image_name}:${GITHUB_SHA::8} ${DOCKER_REGISTRY}/${image_name}:dev-${GITHUB_SHA::8}

      - name: Tag (master)
        if: github.ref == 'refs/heads/master'
        run: docker tag ${DOCKER_REGISTRY}/${image_name}:${GITHUB_SHA::8} ${DOCKER_REGISTRY}/${image_name}:master-${GITHUB_SHA::8} &&
             docker tag ${DOCKER_REGISTRY}/${image_name}:${GITHUB_SHA::8} ${DOCKER_REGISTRY}/${image_name}:latest

      - name: Tag (git tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: DOCKER_TAG=$(echo ${GITHUB_REF} | sed -e 's/refs\/tags\///') &&
             docker tag ${DOCKER_REGISTRY}/${image_name}:${GITHUB_SHA::8} ${DOCKER_REGISTRY}/${image_name}:${GITHUB_REF:10} &&
             docker tag ${DOCKER_REGISTRY}/${image_name}:${GITHUB_SHA::8} ${DOCKER_REGISTRY}/${image_name}:${DOCKER_TAG}

      - name: Push
        run: docker push ${DOCKER_REGISTRY}/${image_name}