name: CI CD

on:
  pull_request:

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-24.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata action
        id: meta
        uses: docker/metadata-action@v5
        with:
          images:
            patroni-exporter-local
          tags: |
            type=raw,latest

      - name: Build Dockerimage
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=/tmp/patroni-exporter-local.tar
          platforms: linux/amd64
          push: false
          tags: ${{ steps.meta.outputs.tags }}

  dependabot-automerge:
    name: Auto Merge (Dependabot)
    needs:
      - docker
    uses: Staffbase/gha-workflows/.github/workflows/template_automerge_dependabot.yml@v8.1.0
    with:
      force: true
    secrets:
      app_id: ${{ vars.STAFFBASE_ACTIONS_APP_ID }}
      private_key: ${{ secrets.STAFFBASE_ACTIONS_PRIVATE_KEY }}
